---
title: "Closeread - try"
format:
  closeread-html:
    theme: cosmo
    css: index-styles.css
    remove-header-space: true
    code-tools: true
---

closeread is a custom format for [Quarto](https://quarto.org/) that enables scrollytelling features for html documents.

Install the extension by running the following command in the directory you wish to use it:

``` bash
quarto add qmd-lab/closeread
```

With the extension installed, you can author documents using the `closeread-html` format:

``` yaml
---
title: My First Closeread
format: closeread-html
---
```

\
\

::: {.cr-section layout="overlay-center" style="font-size: 1.5em; background-color: rgba(39, 128, 227, 0.2);"}
Get your first closeread doc up and running in four steps. @cr-doc

Step one: create a qmd file and set the format to closeread-html. @cr-doc

Step two: open up a closeread section. @cr-doc

Step three: flag an element to become a sticky. @cr-doc

::: {focus-on="cr-doc" highlight="12" style="padding-bottom: 100dvh"}
Step four: create a trigger to make the sticky appear. @cr-doc
:::

::: {#cr-doc filename="myfirstcr.qmd"}
``` markdown
---
title: My First Closeread
format: closeread-html
---

Hello World! Please read my closeread story below.

:::{.cr-section}

Closeread enables scrollytelling.

Draw your readers attention with: @cr-features

:::{#cr-features}
1. Highlighting
2. Zooming
3. Panning
:::

:::
```
:::
:::

\
\
\

For guidance on how to author closeread documents, read the [Guide](guide/index.qmd). For examples of closeread documents alongside their source, see the [Gallery](gallery/index.qmd). For a catalog of the syntax and yaml options used in the closeread extension, see the [Reference](reference/index.qmd).
